name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]  # or 'master', adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed for your project)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Generate version.json
        run: echo "{\"version\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > ./dist/version.json

      - name: Commit version.json
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./dist/version.json
          git commit -m "Update version.json" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
